ДЗ6 Работа с формами
Angular-OTUS/ToDoList-DmitryIvanov pull request #6
Opened 2024-09-28 14:28 UTC by HiDiv

2024-10-03 16:06 UTC, ilya17 requested changes

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list-item/to-do-list-item.component.html
>        (click)="onSelect()"
Мне не нравится решения добавления клика на текст, хотя бы потом, что текст ограничен в твоем примере шириной и я не могу кликнуть на всю область ту-ду, приходится прицеливаться на текст(а если он вообще из одного символа будет?))), подумай, как можно оптимизировать

2024-10-03 16:06 UTC, ilya17 commented on src/app/Shared/components/button/button.component.ts
>    @Input() disabled = false;
@Input() disabled: boolean = false; или @Input() disabled?: boolean;

2024-10-03 16:06 UTC, ilya17 commented on src/app/Shared/components/button/button.component.ts
>    @Output() clickEvent = new EventEmitter();
нет типизации и обозначения public/private, пробежаться по всему проекту и проверить

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-create-item/task-name.directive.ts
> +  validate(control: AbstractControl): ValidationErrors | null {
public validate(....

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-create-item/task-name.directive.ts
> +    const taskName = typeof control.value === 'string' ? control.value.trim() : '';
Создание const тут нецелесообразно, вынеси в метод и пусть он тебе возвращает результат в константе.
Константы создаем, когда код переиспользуем более одного раза или если есть "таинственное число", каждая константа занимает память, минимизируя константы, мы отпимизируем приложение

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-create-item/to-do-create-item.component.ts
> +  @Output() addTaskEvent = new EventEmitter<NewTask>();
public/private, нет типизации

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-create-item/to-do-create-item.component.ts
> +    console.log(newTaskForm);
console.log - убираем

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-create-item/to-do-create-item.component.ts
> +    const { text, description }: NewTask = newTaskForm.value;
тут правильно, константа нужна

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-filter/to-do-filter.component.ts
> +  @Input() value: TaskStatusFilter = [];
public/private

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list-item/to-do-list-item.component.ts
> +  @Input({ required: true }) status!: TaskItemStatus;
public/private
я бы старался не использовать !, используй лучше ?, а то так можно ногу отстрелить себе)) так как ты явно указываешь, что переменная будет иметь значение, а вдруг не будет?)

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list-item/to-do-list-item.component.ts
> +  @Output() changeStatusEvent = new EventEmitter<TaskItemStatus>();
ну ты понял)

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +  private destroy$ = new Subject<void>();
типизация

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        takeUntil(this.destroy$),
я бы  поставил после catchError

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +      .subscribe(taskItems => {
логику можно разместить в tap, как сайдэффект

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +    const nextId = 1 + Math.max(0, ...this.taskItems.map(item => Number(item.id)));
тоже подумай насчет константы

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +      .subscribe(() => {
в tap?

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        takeUntil(this.destroy$),
тоже после

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        takeUntil(this.destroy$),
в конце?

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        if (status === 'Completed') {
давай вынесем то в метод. Не забывай если метод используется только в компоненте методу будет private, проверь по приложению правильно ли ты ставишь на методы private/public

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +    const idx = this.getTaskIdxById(id);
тут используем больше одного раза, можно так делать

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        takeUntil(this.destroy$),
в конец

2024-10-03 16:06 UTC, ilya17 commented on src/app/components/to-do-list/to-do-list.component.ts
> +        this.toastService.showToast({ text: 'The task has been changed', type: 'info' });
в tap?

2024-10-13 14:41 UTC, HiDiv commented on src/app/components/to-do-list-item/to-do-list-item.component.html
>        (click)="onSelect()"
Обернул всю строчку с данными о задаче в div и повесил обработку на него... Попутно переделал немного UI, мне изначально не нравилась идея с двойным кликом, т.ч. добавил справа от текста задачи кнопку-иконку для перехода в режим редактирования по одинарному клику.

2024-10-13 14:43 UTC, HiDiv commented on src/app/components/to-do-create-item/task-name.directive.ts
> +    const taskName = typeof control.value === 'string' ? control.value.trim() : '';
Вынес в отдельный метод, хотя и не совсем согласен с полным отказом от "одноразовых констант"...

2024-10-13 14:44 UTC, HiDiv commented on src/app/components/to-do-create-item/to-do-create-item.component.ts
> +    console.log(newTaskForm);
убрал

2024-10-13 14:45 UTC, HiDiv commented on src/app/components/to-do-list/to-do-list.component.ts
> +  private destroy$ = new Subject<void>();
Поправил руками, где нашел, но линтер, который бы можно было настроить на контроль именно этой ошибки, найти не удалось...

2024-10-13 14:47 UTC, HiDiv commented on src/app/components/to-do-list/to-do-list.component.ts
> +        takeUntil(this.destroy$),
Поменял местами catchError и takeUntil. Интуитивно потенциальная проблема понятна, но достаточных знаний по RxJs пока нет...

2024-10-13 14:47 UTC, HiDiv commented on src/app/components/to-do-list/to-do-list.component.ts
> +      .subscribe(taskItems => {
Тут и ниже, что делает tap пока не разобрался, т.ч. менять ничего не стал...

2024-10-13 14:48 UTC, HiDiv commented on src/app/components/to-do-list/to-do-list.component.ts
> +    const nextId = 1 + Math.max(0, ...this.taskItems.map(item => Number(item.id)));
Вынес в метод

2024-10-13 14:48 UTC, HiDiv commented on src/app/components/to-do-list/to-do-list.component.ts
> +        if (status === 'Completed') {
Вынес в отдельный метод

2024-10-13 17:57 UTC, ilya17 commented on src/app/components/to-do-list-item/to-do-list-item.component.html
>        (click)="onSelect()"
спасибо)

2024-10-13 18:05 UTC, ilya17 commented on src/app/components/to-do-create-item/task-name.directive.ts
> +    const taskName = typeof control.value === 'string' ? control.value.trim() : '';
Да, походу это просто моя "вкусовщина", аргумент принимается, согласен!

2024-10-13 18:12 UTC, ilya17 commented on src/app/Shared/components/button/button.component.ts
> +  @Input() public disabled?: boolean = false;
@Input() public disabled?: boolean;
Если по умолчанию false можно не присваивать явно значение false

2024-10-15 10:12 UTC, merged